language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml tests/
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: I/sjRIdCb8bSe4Z9j7xm5VVv9kvrP81IIIFQo/H+koL2lBSL1y7497YnkmC14pOqoojbKUXEaYRokeyykVtYNDBcC9Z2ThO8TZ68ZpefsrQ1NJViB+BSqR+kGQsRH+KtdPQEgKCSFHWSJ0g8c8OAaCqnpH+fJhhpUhxOY1C2ecLZWaNW/oXS3zoDTD3KM/9JjRU7t2LBGv5JQYt5QcerACT++TqNEeqVj8YTevqe26swDV/JUg/hRoAJ8ukCTYOM+Bgm4Vne29ZElSJFfyRASGTP/fDbctVRHxZ4mX5Ys4rTJH/JnYJZss1/q2C8IJuGKJHUVRsyU4J8TJwsrkVB7FXgn+wgB9ZkZ0JrmcHywhaChDUH8KQft16uE84cjHxHlWiCUqqLMplKcFCPLeLY/vi6Lvup0ol15z8OBbJlia/Cb6Y5/1vT/iPwXyMQu8sFtft5JTSH7751Gc/m3IkxOoz8HIrwVxEDcISBUlV4E45ryQv64J1Oy0RpreUTMnaaHs1TtOoFgWjRziSB6PYb0xCJk3fHvYHsI9bC7YuFqdLMoQDWFqHDk1sA5m3I2tzY+s4xSpdZcCj//6hKWq8Sx9Tp7Z6KIk9yRJ2rvXpin/eD5PYOg6fBaes0is2jwWRYUWK31qhPBeEsvaw/4bScljtnKbCZRCVHgrWisK+O50w=
  on:
    tags: true
    branch: master
