language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml tests/
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: nSK+Jv45IfbeITQM6/OvpVFpv18W/aglldUQiOIlrsmpbLs7Jc9DRilfyXHGDv4mrA8wOlkqR74SafDD+4pY4dgLHD0dYbvoKwHB94swKAhuNp1HXbuuWpOg2Fd/AJjOdfivcfOK4fpF1cn2iv9vvzRUwyxh21tW7deB8IMPqEJNtHzi2JXRgBeaPFw9NY37HR3MhLMpmtYVv7jR7nwUUy2w5Bw4X3GIpiLaWE94J/e221qKcRX5sodycZ/XLbIMw0vaFZ4WAnXLGs3BFfxaQx3t6nMQtpvaEVts84jz9baS2cCWYWz1sx+gnn7ytFg6+IeZKhkb8ORO4sRT5ryHejhUwiw0KI7wfG5zqJqPODAnnTBegXGVvm7ecYHgbiZjaHbNtmB0YYhe2uI7eckpaO28gtqQVERawXp2P5C+i+pjuA7k0ETFicTD+U6MZhpqeXHU9iPnCNNWy++8DPUAJla/tB78xfJ1Oerf6Y+KRgUD9Ysl9jUmQzkoPi/SGlNN4fURmlSqEtiOwC5W29uzbDnf+olLMHVck+HRJC4fTbYi47/KJU85dkVcAO/RMXsmIBUHf0FYhk3h3W8d1CAIQBtLWD95ebHgJafvNRNNVr9UaTOYzMA24IrC0FYxajchj/A0kVh0TsoobwtDy8E8O8cOP2f0zzhUmblBGxeDG7c=
  on:
    tags: true
    branch: master
